/**
 * This file was generated
 */
export enum ISymbolShipReactor {
    'REACTOR_SOLAR_I' = 'REACTOR_SOLAR_I',
    'REACTOR_FUSION_I' = 'REACTOR_FUSION_I',
    'REACTOR_FISSION_I' = 'REACTOR_FISSION_I',
    'REACTOR_CHEMICAL_I' = 'REACTOR_CHEMICAL_I',
    'REACTOR_ANTIMATTER_I' = 'REACTOR_ANTIMATTER_I',
}
