/**
 * This file was generated by st-open-api
 */

/**
 * Open-api schema
 * {
 *   "description": "",
 *   "type": "object",
 *   "properties": {
 *     "accountId": {
 *       "type": "string",
 *       "minLength": 1
 *     },
 *     "symbol": {
 *       "type": "string",
 *       "minLength": 1
 *     },
 *     "headquarters": {
 *       "type": "string",
 *       "minLength": 1,
 *       "description": "The headquarters of the agent."
 *     },
 *     "credits": {
 *       "type": "integer",
 *       "description": "The number of credits the agent has available. Credits can be negative if funds have been overdrawn."
 *     }
 *   },
 *   "required": [
 *     "accountId",
 *     "symbol",
 *     "headquarters",
 *     "credits"
 *   ]
 * }
 */
export interface Agent {

    /**
     * open-api validation:
     *   - minLength: 1
     */
    accountId: string;

    /**
     * The number of credits the agent has available. Credits can be negative if funds have been overdrawn.
     */
    credits: number;

    /**
     * The headquarters of the agent.
     * open-api validation:
     *   - minLength: 1
     */
    headquarters: string;

    /**
     * open-api validation:
     *   - minLength: 1
     */
    symbol: string;

}
