/**
 * This file was generated by st-open-api
 */

/**
 * Open-api schema
 * {
 *   "type": "object",
 *   "description": "The chart of a system or waypoint, which makes the location visible to other agents.",
 *   "properties": {
 *     "waypointSymbol": {
 *       "type": "string"
 *     },
 *     "submittedBy": {
 *       "type": "string"
 *     },
 *     "submittedOn": {
 *       "type": "string",
 *       "format": "date-time"
 *     }
 *   }
 * }
 */
export interface Chart {

    submittedBy?: string;

    /**
     * open-api format: date-time
     */
    submittedOn?: Date;

    waypointSymbol?: string;

}
