/**
 * This file was generated by st-open-api
 */
import { ContractDeliverGood } from './ContractDeliverGood'
import { ContractPayment } from './ContractPayment'

/**
 * Open-api schema
 * {
 *   "type": "object",
 *   "properties": {
 *     "deadline": {
 *       "type": "string",
 *       "format": "date-time",
 *       "description": "The deadline for the contract."
 *     },
 *     "payment": {
 *       "$ref": "#/components/schemas/ContractPayment"
 *     },
 *     "deliver": {
 *       "type": "array",
 *       "items": {
 *         "$ref": "#/components/schemas/ContractDeliverGood"
 *       }
 *     }
 *   },
 *   "required": [
 *     "deadline",
 *     "payment"
 *   ]
 * }
 */
export interface ContractTerms {

    /**
     * The deadline for the contract.
     * open-api format: date-time
     */
    deadline: Date;

    deliver?: Array<ContractDeliverGood>;

    payment: ContractPayment;

}
