/**
 * This file was generated by st-open-api
 */

/**
 * Open-api schema
 * {
 *   "type": "object",
 *   "properties": {
 *     "onAccepted": {
 *       "type": "integer",
 *       "description": "The amount of credits received up front for accepting the contract."
 *     },
 *     "onFulfilled": {
 *       "type": "integer",
 *       "description": "The amount of credits received when the contract is fulfilled."
 *     }
 *   },
 *   "required": [
 *     "onAccepted",
 *     "onFulfilled"
 *   ]
 * }
 */
export interface ContractPayment {

    /**
     * The amount of credits received up front for accepting the contract.
     */
    onAccepted: number;

    /**
     * The amount of credits received when the contract is fulfilled.
     */
    onFulfilled: number;

}
