/**
 * This file was generated by st-open-api
 */
import { ExtractionYield } from './ExtractionYield'

/**
 * Open-api schema
 * {
 *   "description": "",
 *   "type": "object",
 *   "properties": {
 *     "shipSymbol": {
 *       "type": "string",
 *       "minLength": 1
 *     },
 *     "yield": {
 *       "$ref": "#/components/schemas/ExtractionYield"
 *     }
 *   },
 *   "required": [
 *     "shipSymbol",
 *     "yield"
 *   ]
 * }
 */
export interface Extraction {

    /**
     * open-api validation:
     *   - minLength: 1
     */
    shipSymbol: string;

    yield: ExtractionYield;

}
