/**
 * This file was generated by st-open-api
 */

/**
 * Open-api schema
 * {
 *   "type": "object",
 *   "properties": {
 *     "symbol": {
 *       "type": "string",
 *       "minLength": 1
 *     },
 *     "units": {
 *       "type": "integer",
 *       "description": "The number of units extracted that were placed into the ship's cargo hold."
 *     }
 *   },
 *   "required": [
 *     "symbol",
 *     "units"
 *   ]
 * }
 */
export interface ExtractionYield {

    /**
     * open-api validation:
     *   - minLength: 1
     */
    symbol: string;

    /**
     * The number of units extracted that were placed into the ship's cargo hold.
     */
    units: number;

}
