/**
 * This file was generated by st-open-api
 */
import { FactionTrait } from './FactionTrait'

/**
 * Open-api schema
 * {
 *   "description": "",
 *   "type": "object",
 *   "properties": {
 *     "symbol": {
 *       "type": "string",
 *       "minLength": 1
 *     },
 *     "name": {
 *       "type": "string",
 *       "minLength": 1
 *     },
 *     "description": {
 *       "type": "string",
 *       "minLength": 1
 *     },
 *     "headquarters": {
 *       "type": "string",
 *       "minLength": 1
 *     },
 *     "traits": {
 *       "type": "array",
 *       "items": {
 *         "$ref": "#/components/schemas/FactionTrait"
 *       }
 *     }
 *   },
 *   "required": [
 *     "symbol",
 *     "name",
 *     "description",
 *     "headquarters",
 *     "traits"
 *   ]
 * }
 */
export interface Faction {

    /**
     * open-api validation:
     *   - minLength: 1
     */
    description: string;

    /**
     * open-api validation:
     *   - minLength: 1
     */
    headquarters: string;

    /**
     * open-api validation:
     *   - minLength: 1
     */
    name: string;

    /**
     * open-api validation:
     *   - minLength: 1
     */
    symbol: string;

    traits: Array<FactionTrait>;

}
