/**
 * This file was generated by st-open-api
 */

export interface IContractDeliverGood {

    destinationSymbol: string;

    tradeSymbol: string;

    unitsFulfilled: number;

    unitsRequired: number;

}
