/**
 * This file was generated by st-open-api
 */
import {IContractPayment} from './i-contract-payment';

export interface IContractTerms {

    deadline: string;

    deliver?: Array<any>;

    payment: IContractPayment;

}
