/**
 * This file was generated by st-open-api
 */
import {IContractTerms} from './i-contract-terms';
import {ITypeContract} from './enumeration/i-type-contract';

export interface IContract {

    accepted: boolean;

    expiration: string;

    factionSymbol: string;

    fulfilled: boolean;

    id: string;

    terms: IContractTerms;

    type: ITypeContract;

}
