/**
 * This file was generated by st-open-api
 */

export interface IFaction {

    description: string;

    headquarters: string;

    name: string;

    symbol: string;

    traits: Array<any>;

}
