/**
 * This file was generated by st-open-api
 */
import {ISymbolFactionTrait} from './enumeration/i-symbol-faction-trait';

export interface IFactionTrait {

    description: string;

    name: string;

    symbol: ISymbolFactionTrait;

}
