/**
 * This file was generated by st-open-api
 */
import {ITypeMarketTransaction} from './enumeration/i-type-market-transaction';

export interface IMarketTransaction {

    pricePerUnit: number;

    shipSymbol: string;

    timestamp: string;

    totalPrice: number;

    tradeSymbol: string;

    type: ITypeMarketTransaction;

    units: number;

    waypointSymbol: string;

}
