/**
 * This file was generated by st-open-api
 */
import {ISupplyMarketTradeGood} from './enumeration/i-supply-market-trade-good';

export interface IMarketTradeGood {

    purchasePrice: number;

    sellPrice: number;

    supply: ISupplyMarketTradeGood;

    symbol: string;

    tradeVolume: number;

}
