/**
 * This file was generated by st-open-api
 */

export interface IMarket {

    exchange: Array<any>;

    exports: Array<any>;

    imports: Array<any>;

    symbol: string;

    tradeGoods?: Array<any>;

    transactions?: Array<any>;

}
