/**
 * This file was generated by st-open-api
 */
import {IShipRole} from './i-ship-role';

export interface IShipRegistration {

    factionSymbol: string;

    name: string;

    role: IShipRole;

}
