/**
 * This file was generated by st-open-api
 */
import {IShipTypesShipyard} from './interface/i-ship-types-shipyard';

export interface IShipyard {

    ships?: Array<any>;

    shipTypes: Array<IShipTypesShipyard>;

    symbol: string;

    transactions?: Array<any>;

}
