/**
 * This file was generated by st-open-api
 */
import {IConsumedShipFuel} from './interface/i-consumed-ship-fuel';

export interface IShipFuel {

    capacity: number;

    consumed?: IConsumedShipFuel;

    current: number;

}
