/**
 * This file was generated by st-open-api
 */
import {IRotationShipCrew} from './enumeration/i-rotation-ship-crew';

export interface IShipCrew {

    capacity: number;

    current: number;

    morale: number;

    required: number;

    rotation: IRotationShipCrew;

    wages: number;

}
