/**
 * This file was generated by st-open-api
 */
import {IShipCondition} from './i-ship-condition';
import {IShipRequirements} from './i-ship-requirements';
import {ISymbolShipEngine} from './enumeration/i-symbol-ship-engine';

export interface IShipEngine {

    condition?: IShipCondition;

    description: string;

    name: string;

    requirements: IShipRequirements;

    speed: number;

    symbol: ISymbolShipEngine;

}
