/**
 * This file was generated by st-open-api
 */
import {IWaypointType} from './i-waypoint-type';

export interface IShipNavRouteWaypoint {

    symbol: string;

    systemSymbol: string;

    type: IWaypointType;

    x: number;

    y: number;

}
