/**
 * This file was generated by st-open-api
 */
import {IShipCargo} from './i-ship-cargo';
import {IShipCrew} from './i-ship-crew';
import {IShipEngine} from './i-ship-engine';
import {IShipFrame} from './i-ship-frame';
import {IShipFuel} from './i-ship-fuel';
import {IShipNav} from './i-ship-nav';
import {IShipReactor} from './i-ship-reactor';
import {IShipRegistration} from './i-ship-registration';

export interface IShip {

    cargo: IShipCargo;

    crew: IShipCrew;

    engine: IShipEngine;

    frame: IShipFrame;

    fuel: IShipFuel;

    modules: Array<any>;

    mounts: Array<any>;

    nav: IShipNav;

    reactor: IShipReactor;

    registration: IShipRegistration;

    symbol: string;

}
