/**
 * This file was generated by st-open-api
 */
import {IShipRequirements} from './i-ship-requirements';
import {ISymbolShipMount} from './enumeration/i-symbol-ship-mount';

export interface IShipMount {

    deposits?: Array<string>;

    description?: string;

    name: string;

    requirements: IShipRequirements;

    strength?: number;

    symbol: ISymbolShipMount;

}
