/**
 * This file was generated by st-open-api
 */
import {IShipEngine} from './i-ship-engine';
import {IShipFrame} from './i-ship-frame';
import {IShipReactor} from './i-ship-reactor';
import {IShipType} from './i-ship-type';

export interface IShipyardShip {

    description: string;

    engine: IShipEngine;

    frame: IShipFrame;

    modules: Array<any>;

    mounts: Array<any>;

    name: string;

    purchasePrice: number;

    reactor: IShipReactor;

    type?: IShipType;

}
