/**
 * This file was generated by st-open-api
 */
import {IShipCondition} from './i-ship-condition';
import {IShipRequirements} from './i-ship-requirements';
import {ISymbolShipReactor} from './enumeration/i-symbol-ship-reactor';

export interface IShipReactor {

    condition?: IShipCondition;

    description: string;

    name: string;

    powerOutput: number;

    requirements: IShipRequirements;

    symbol: ISymbolShipReactor;

}
