/**
 * This file was generated by st-open-api
 */

export interface IShipyardTransaction {

    agentSymbol: string;

    price: number;

    shipSymbol: string;

    timestamp: string;

    waypointSymbol: string;

}
