/**
 * This file was generated by st-open-api
 */
import {ISystemType} from './i-system-type';

export interface ISystem {

    factions: Array<any>;

    sectorSymbol: string;

    symbol: string;

    type: ISystemType;

    waypoints: Array<any>;

    x: number;

    y: number;

}
