/**
 * This file was generated by st-open-api
 */
import {ITradeSymbol} from './i-trade-symbol';

export interface ITradeGood {

    description: string;

    name: string;

    symbol: ITradeSymbol;

}
