/**
 * This file was generated by st-open-api
 */
import {ISymbolWaypointTrait} from './enumeration/i-symbol-waypoint-trait';

export interface IWaypointTrait {

    description: string;

    name: string;

    symbol: ISymbolWaypointTrait;

}
