/**
 * This file was generated by st-open-api
 */
import {IChart} from './i-chart';
import {IWaypointFaction} from './i-waypoint-faction';
import {IWaypointType} from './i-waypoint-type';

export interface IWaypoint {

    chart?: IChart;

    faction?: IWaypointFaction;

    orbitals: Array<any>;

    symbol: string;

    systemSymbol: string;

    traits: Array<any>;

    type: IWaypointType;

    x: number;

    y: number;

}
