/**
 * This file was generated by st-open-api
 */
import { ConnectedSystem } from './ConnectedSystem'

/**
 * Open-api schema
 * {
 *   "type": "object",
 *   "description": "",
 *   "properties": {
 *     "jumpRange": {
 *       "type": "number",
 *       "description": "The maximum jump range of the gate."
 *     },
 *     "factionSymbol": {
 *       "type": "string",
 *       "description": "The symbol of the faction that owns the gate."
 *     },
 *     "connectedSystems": {
 *       "type": "array",
 *       "description": "The systems within range of the gate that have a corresponding gate.",
 *       "items": {
 *         "$ref": "#/components/schemas/ConnectedSystem"
 *       }
 *     }
 *   },
 *   "required": [
 *     "jumpRange",
 *     "connectedSystems"
 *   ]
 * }
 */
export interface JumpGate {

    /**
     * The systems within range of the gate that have a corresponding gate.
     */
    connectedSystems: Array<ConnectedSystem>;

    /**
     * The symbol of the faction that owns the gate.
     */
    factionSymbol?: string;

    /**
     * The maximum jump range of the gate.
     */
    jumpRange: number;

}
