/**
 * This file was generated by st-open-api
 */
import { Chart } from './Chart'
import { WaypointFaction } from './WaypointFaction'
import { WaypointOrbital } from './WaypointOrbital'
import { WaypointTrait } from './WaypointTrait'
import { WaypointType } from './WaypointType'

/**
 * Open-api schema
 * {
 *   "description": "A waypoint is a location that ships can travel to such as a Planet, Moon or Space Station.",
 *   "type": "object",
 *   "properties": {
 *     "symbol": {
 *       "type": "string",
 *       "minLength": 1
 *     },
 *     "type": {
 *       "$ref": "#/components/schemas/WaypointType"
 *     },
 *     "systemSymbol": {
 *       "type": "string",
 *       "minLength": 1
 *     },
 *     "x": {
 *       "type": "integer"
 *     },
 *     "y": {
 *       "type": "integer"
 *     },
 *     "orbitals": {
 *       "type": "array",
 *       "items": {
 *         "$ref": "#/components/schemas/WaypointOrbital"
 *       }
 *     },
 *     "faction": {
 *       "$ref": "#/components/schemas/WaypointFaction"
 *     },
 *     "traits": {
 *       "type": "array",
 *       "description": "The traits of the waypoint.",
 *       "items": {
 *         "$ref": "#/components/schemas/WaypointTrait"
 *       }
 *     },
 *     "chart": {
 *       "$ref": "#/components/schemas/Chart"
 *     }
 *   },
 *   "required": [
 *     "symbol",
 *     "type",
 *     "systemSymbol",
 *     "x",
 *     "y",
 *     "orbitals",
 *     "traits"
 *   ]
 * }
 */
export interface ScannedWaypoint {

    chart?: Chart;

    faction?: WaypointFaction;

    orbitals: Array<WaypointOrbital>;

    /**
     * open-api validation:
     *   - minLength: 1
     */
    symbol: string;

    /**
     * open-api validation:
     *   - minLength: 1
     */
    systemSymbol: string;

    /**
     * The traits of the waypoint.
     */
    traits: Array<WaypointTrait>;

    type: WaypointType;

    x: number;

    y: number;

}
