/**
 * This file was generated by st-open-api
 */

/**
 * Open-api schema
 * {
 *   "type": "object",
 *   "description": "A mount on the ship.",
 *   "properties": {
 *     "symbol": {
 *       "type": "string"
 *     }
 *   },
 *   "required": [
 *     "symbol"
 *   ]
 * }
 */
export interface ScannedShipMounts {

    symbol: string;

}
