/**
 * This file was generated by st-open-api
 */
import { ShipEngine } from './ShipEngine'
import { ShipFrame } from './ShipFrame'
import { ShipModule } from './ShipModule'
import { ShipMount } from './ShipMount'
import { ShipReactor } from './ShipReactor'
import { ShipType } from './ShipType'

/**
 * Open-api schema
 * {
 *   "description": "",
 *   "type": "object",
 *   "properties": {
 *     "type": {
 *       "$ref": "#/components/schemas/ShipType"
 *     },
 *     "name": {
 *       "type": "string"
 *     },
 *     "description": {
 *       "type": "string"
 *     },
 *     "purchasePrice": {
 *       "type": "integer"
 *     },
 *     "frame": {
 *       "$ref": "#/components/schemas/ShipFrame"
 *     },
 *     "reactor": {
 *       "$ref": "#/components/schemas/ShipReactor"
 *     },
 *     "engine": {
 *       "$ref": "#/components/schemas/ShipEngine"
 *     },
 *     "modules": {
 *       "type": "array",
 *       "items": {
 *         "$ref": "#/components/schemas/ShipModule"
 *       }
 *     },
 *     "mounts": {
 *       "type": "array",
 *       "items": {
 *         "$ref": "#/components/schemas/ShipMount"
 *       }
 *     }
 *   },
 *   "required": [
 *     "symbol",
 *     "name",
 *     "description",
 *     "purchasePrice",
 *     "frame",
 *     "reactor",
 *     "engine",
 *     "modules",
 *     "mounts"
 *   ]
 * }
 */
export interface ShipyardShip {

    description: string;

    engine: ShipEngine;

    frame: ShipFrame;

    modules: Array<ShipModule>;

    mounts: Array<ShipMount>;

    name: string;

    purchasePrice: number;

    reactor: ShipReactor;

    type?: ShipType;

}
