/**
 * This file was generated by st-open-api
 */
import { ShipyardShip } from './ShipyardShip'
import { ShipyardShipTypes } from './ShipyardShipTypes'
import { ShipyardTransaction } from './ShipyardTransaction'

/**
 * Open-api schema
 * {
 *   "description": "",
 *   "type": "object",
 *   "properties": {
 *     "symbol": {
 *       "type": "string",
 *       "description": "The symbol of the shipyard. The symbol is the same as the waypoint where the shipyard is located.",
 *       "minLength": 1
 *     },
 *     "shipTypes": {
 *       "type": "array",
 *       "description": "The list of ship types available for purchase at this shipyard.",
 *       "items": {
 *         "type": "object",
 *         "properties": {
 *           "type": {
 *             "$ref": "#/components/schemas/ShipType"
 *           }
 *         }
 *       }
 *     },
 *     "transactions": {
 *       "type": "array",
 *       "description": "The list of recent transactions at this shipyard.",
 *       "items": {
 *         "$ref": "#/components/schemas/ShipyardTransaction"
 *       }
 *     },
 *     "ships": {
 *       "type": "array",
 *       "description": "The ships that are currently available for purchase at the shipyard.",
 *       "items": {
 *         "$ref": "#/components/schemas/ShipyardShip"
 *       }
 *     }
 *   },
 *   "required": [
 *     "symbol",
 *     "shipTypes"
 *   ]
 * }
 */
export interface Shipyard {

    /**
     * The ships that are currently available for purchase at the shipyard.
     */
    ships?: Array<ShipyardShip>;

    /**
     * The list of ship types available for purchase at this shipyard.
     */
    shipTypes: Array<ShipyardShipTypes>;

    /**
     * The symbol of the shipyard. The symbol is the same as the waypoint where the shipyard is located.
     * open-api validation:
     *   - minLength: 1
     */
    symbol: string;

    /**
     * The list of recent transactions at this shipyard.
     */
    transactions?: Array<ShipyardTransaction>;

}
