/**
 * This file was generated by st-open-api
 */
import { ShipCondition } from './ShipCondition'
import { ShipReactorSymbol } from './ShipReactorSymbol'
import { ShipRequirements } from './ShipRequirements'

/**
 * Open-api schema
 * {
 *   "type": "object",
 *   "description": "The reactor of the ship. The reactor is responsible for powering the ship's systems and weapons.",
 *   "properties": {
 *     "symbol": {
 *       "type": "string",
 *       "enum": [
 *         "REACTOR_SOLAR_I",
 *         "REACTOR_FUSION_I",
 *         "REACTOR_FISSION_I",
 *         "REACTOR_CHEMICAL_I",
 *         "REACTOR_ANTIMATTER_I"
 *       ]
 *     },
 *     "name": {
 *       "type": "string"
 *     },
 *     "description": {
 *       "type": "string"
 *     },
 *     "condition": {
 *       "$ref": "#/components/schemas/ShipCondition"
 *     },
 *     "powerOutput": {
 *       "type": "integer",
 *       "minimum": 1
 *     },
 *     "requirements": {
 *       "$ref": "#/components/schemas/ShipRequirements"
 *     }
 *   },
 *   "required": [
 *     "symbol",
 *     "name",
 *     "description",
 *     "powerOutput",
 *     "requirements"
 *   ]
 * }
 */
export interface ShipReactor {

    condition?: ShipCondition;

    description: string;

    name: string;

    /**
     * open-api validation:
     *   - minimum: 1
     */
    powerOutput: number;

    requirements: ShipRequirements;

    symbol: ShipReactorSymbol;

}
