/**
 * This file was generated by st-open-api
 */

/**
 * Open-api schema
 * {
 *   "type": "object",
 *   "description": "The requirements for installation on a ship",
 *   "properties": {
 *     "power": {
 *       "type": "integer",
 *       "description": "The amount of power required from the reactor."
 *     },
 *     "crew": {
 *       "type": "integer",
 *       "description": "The number of crew required for operation."
 *     },
 *     "slots": {
 *       "type": "integer",
 *       "description": "The number of module slots required for installation."
 *     }
 *   }
 * }
 */
export interface ShipRequirements {

    /**
     * The number of crew required for operation.
     */
    crew?: number;

    /**
     * The amount of power required from the reactor.
     */
    power?: number;

    /**
     * The number of module slots required for installation.
     */
    slots?: number;

}
