/**
 * This file was generated by st-open-api
 */

/**
 * Open-api schema
 * {
 *   "type": "object",
 *   "description": "The type of cargo item and the number of units.",
 *   "properties": {
 *     "symbol": {
 *       "type": "string",
 *       "description": "The unique identifier of the cargo item type."
 *     },
 *     "name": {
 *       "type": "string",
 *       "description": "The name of the cargo item type."
 *     },
 *     "description": {
 *       "type": "string",
 *       "description": "The description of the cargo item type."
 *     },
 *     "units": {
 *       "type": "integer",
 *       "description": "The number of units of the cargo item.",
 *       "minimum": 1
 *     }
 *   },
 *   "required": [
 *     "symbol",
 *     "name",
 *     "description",
 *     "units"
 *   ]
 * }
 */
export interface ShipCargoItem {

    /**
     * The description of the cargo item type.
     */
    description: string;

    /**
     * The name of the cargo item type.
     */
    name: string;

    /**
     * The unique identifier of the cargo item type.
     */
    symbol: string;

    /**
     * The number of units of the cargo item.
     * open-api validation:
     *   - minimum: 1
     */
    units: number;

}
