/**
 * This file was generated by st-open-api
 */
import { ShipCondition } from './ShipCondition'
import { ShipEngineSymbol } from './ShipEngineSymbol'
import { ShipRequirements } from './ShipRequirements'

/**
 * Open-api schema
 * {
 *   "type": "object",
 *   "description": "The engine determines how quickly a ship travels between waypoints.",
 *   "properties": {
 *     "symbol": {
 *       "type": "string",
 *       "enum": [
 *         "ENGINE_IMPULSE_DRIVE_I",
 *         "ENGINE_ION_DRIVE_I",
 *         "ENGINE_ION_DRIVE_II",
 *         "ENGINE_HYPER_DRIVE_I"
 *       ]
 *     },
 *     "name": {
 *       "type": "string"
 *     },
 *     "description": {
 *       "type": "string"
 *     },
 *     "condition": {
 *       "$ref": "#/components/schemas/ShipCondition"
 *     },
 *     "speed": {
 *       "type": "number",
 *       "minimum": 1
 *     },
 *     "requirements": {
 *       "$ref": "#/components/schemas/ShipRequirements"
 *     }
 *   },
 *   "required": [
 *     "symbol",
 *     "name",
 *     "description",
 *     "speed",
 *     "requirements"
 *   ]
 * }
 */
export interface ShipEngine {

    condition?: ShipCondition;

    description: string;

    name: string;

    requirements: ShipRequirements;

    /**
     * open-api validation:
     *   - minimum: 1
     */
    speed: number;

    symbol: ShipEngineSymbol;

}
