/**
 * This file was generated by st-open-api
 */
import { ShipNavRouteWaypoint } from './ShipNavRouteWaypoint'

/**
 * Open-api schema
 * {
 *   "type": "object",
 *   "description": "The routing information for the ship's most recent transit or current location.",
 *   "properties": {
 *     "destination": {
 *       "$ref": "#/components/schemas/ShipNavRouteWaypoint"
 *     },
 *     "departure": {
 *       "$ref": "#/components/schemas/ShipNavRouteWaypoint"
 *     },
 *     "departureTime": {
 *       "type": "string",
 *       "format": "date-time",
 *       "description": "The date time of the ship's departure."
 *     },
 *     "arrival": {
 *       "type": "string",
 *       "format": "date-time",
 *       "description": "The date time of the ship's arrival. If the ship is in-transit, this is the expected time of arrival."
 *     }
 *   },
 *   "required": [
 *     "destination",
 *     "departure",
 *     "departureTime",
 *     "arrival"
 *   ]
 * }
 */
export interface ShipNavRoute {

    /**
     * The date time of the ship's arrival. If the ship is in-transit, this is the expected time of arrival.
     * open-api format: date-time
     */
    arrival: Date;

    departure: ShipNavRouteWaypoint;

    /**
     * The date time of the ship's departure.
     * open-api format: date-time
     */
    departureTime: Date;

    destination: ShipNavRouteWaypoint;

}
