/**
 * This file was generated by st-open-api
 */
import { ShipRole } from './ShipRole'

/**
 * Open-api schema
 * {
 *   "type": "object",
 *   "description": "The public registration information of the ship",
 *   "properties": {
 *     "name": {
 *       "type": "string",
 *       "description": "The agent's registered name of the ship",
 *       "minLength": 1
 *     },
 *     "factionSymbol": {
 *       "type": "string",
 *       "description": "The symbol of the faction the ship is registered with",
 *       "minLength": 1
 *     },
 *     "role": {
 *       "$ref": "#/components/schemas/ShipRole"
 *     }
 *   },
 *   "required": [
 *     "name",
 *     "factionSymbol",
 *     "role"
 *   ]
 * }
 */
export interface ShipRegistration {

    /**
     * The symbol of the faction the ship is registered with
     * open-api validation:
     *   - minLength: 1
     */
    factionSymbol: string;

    /**
     * The agent's registered name of the ship
     * open-api validation:
     *   - minLength: 1
     */
    name: string;

    role: ShipRole;

}
