/**
 * This file was generated by st-open-api
 */
import { ShipNavFlightMode } from './ShipNavFlightMode'
import { ShipNavRoute } from './ShipNavRoute'
import { ShipNavStatus } from './ShipNavStatus'

/**
 * Open-api schema
 * {
 *   "type": "object",
 *   "description": "The navigation information of the ship.",
 *   "properties": {
 *     "systemSymbol": {
 *       "type": "string",
 *       "description": "The system symbol of the ship's current location."
 *     },
 *     "waypointSymbol": {
 *       "type": "string",
 *       "description": "The waypoint symbol of the ship's current location, or if the ship is in-transit, the waypoint symbol of the ship's destination."
 *     },
 *     "route": {
 *       "$ref": "#/components/schemas/ShipNavRoute"
 *     },
 *     "status": {
 *       "$ref": "#/components/schemas/ShipNavStatus"
 *     },
 *     "flightMode": {
 *       "$ref": "#/components/schemas/ShipNavFlightMode"
 *     }
 *   },
 *   "required": [
 *     "systemSymbol",
 *     "waypointSymbol",
 *     "route",
 *     "status",
 *     "flightMode"
 *   ]
 * }
 */
export interface ShipNav {

    flightMode: ShipNavFlightMode;

    route: ShipNavRoute;

    status: ShipNavStatus;

    /**
     * The system symbol of the ship's current location.
     */
    systemSymbol: string;

    /**
     * The waypoint symbol of the ship's current location, or if the ship is in-transit, the waypoint symbol of the ship's destination.
     */
    waypointSymbol: string;

}
