/**
 * This file was generated by st-open-api
 */
import { WaypointType } from './WaypointType'

/**
 * Open-api schema
 * {
 *   "description": "The destination or departure of a ships nav route.",
 *   "type": "object",
 *   "properties": {
 *     "symbol": {
 *       "type": "string",
 *       "minLength": 1
 *     },
 *     "type": {
 *       "$ref": "#/components/schemas/WaypointType"
 *     },
 *     "systemSymbol": {
 *       "type": "string",
 *       "minLength": 1
 *     },
 *     "x": {
 *       "type": "integer"
 *     },
 *     "y": {
 *       "type": "integer"
 *     }
 *   },
 *   "required": [
 *     "symbol",
 *     "type",
 *     "systemSymbol",
 *     "x",
 *     "y"
 *   ]
 * }
 */
export interface ShipNavRouteWaypoint {

    /**
     * open-api validation:
     *   - minLength: 1
     */
    symbol: string;

    /**
     * open-api validation:
     *   - minLength: 1
     */
    systemSymbol: string;

    type: WaypointType;

    x: number;

    y: number;

}
