/**
 * This file was generated by st-open-api
 */
import { ShipCargoItem } from './ShipCargoItem'

/**
 * Open-api schema
 * {
 *   "type": "object",
 *   "properties": {
 *     "capacity": {
 *       "type": "integer",
 *       "description": "The max number of items that can be stored in the cargo hold.",
 *       "minimum": 0
 *     },
 *     "units": {
 *       "type": "integer",
 *       "description": "The number of items currently stored in the cargo hold.",
 *       "minimum": 0
 *     },
 *     "inventory": {
 *       "type": "array",
 *       "description": "The items currently in the cargo hold.",
 *       "items": {
 *         "$ref": "#/components/schemas/ShipCargoItem"
 *       }
 *     }
 *   },
 *   "required": [
 *     "capacity",
 *     "units",
 *     "inventory"
 *   ]
 * }
 */
export interface ShipCargo {

    /**
     * The max number of items that can be stored in the cargo hold.
     * open-api validation:
     *   - minimum: 0
     */
    capacity: number;

    /**
     * The items currently in the cargo hold.
     */
    inventory: Array<ShipCargoItem>;

    /**
     * The number of items currently stored in the cargo hold.
     * open-api validation:
     *   - minimum: 0
     */
    units: number;

}
