/**
 * This file was generated by st-open-api
 */
import { ShipCargo } from './ShipCargo'
import { ShipCrew } from './ShipCrew'
import { ShipEngine } from './ShipEngine'
import { ShipFrame } from './ShipFrame'
import { ShipFuel } from './ShipFuel'
import { ShipModule } from './ShipModule'
import { ShipMount } from './ShipMount'
import { ShipNav } from './ShipNav'
import { ShipReactor } from './ShipReactor'
import { ShipRegistration } from './ShipRegistration'

/**
 * Open-api schema
 * {
 *   "description": "A ship",
 *   "type": "object",
 *   "properties": {
 *     "symbol": {
 *       "type": "string",
 *       "description": "The globally unique identifier of the ship in the following format: `[AGENT_SYMBOL]_[HEX_ID]`"
 *     },
 *     "registration": {
 *       "$ref": "#/components/schemas/ShipRegistration"
 *     },
 *     "nav": {
 *       "$ref": "#/components/schemas/ShipNav"
 *     },
 *     "crew": {
 *       "$ref": "#/components/schemas/ShipCrew"
 *     },
 *     "frame": {
 *       "$ref": "#/components/schemas/ShipFrame"
 *     },
 *     "reactor": {
 *       "$ref": "#/components/schemas/ShipReactor"
 *     },
 *     "engine": {
 *       "$ref": "#/components/schemas/ShipEngine"
 *     },
 *     "modules": {
 *       "type": "array",
 *       "items": {
 *         "$ref": "#/components/schemas/ShipModule"
 *       }
 *     },
 *     "mounts": {
 *       "type": "array",
 *       "items": {
 *         "$ref": "#/components/schemas/ShipMount"
 *       }
 *     },
 *     "cargo": {
 *       "$ref": "#/components/schemas/ShipCargo"
 *     },
 *     "fuel": {
 *       "$ref": "#/components/schemas/ShipFuel"
 *     }
 *   },
 *   "required": [
 *     "symbol",
 *     "registration",
 *     "nav",
 *     "crew",
 *     "frame",
 *     "reactor",
 *     "engine",
 *     "modules",
 *     "mounts",
 *     "cargo",
 *     "fuel"
 *   ]
 * }
 */
export interface Ship {

    cargo: ShipCargo;

    crew: ShipCrew;

    engine: ShipEngine;

    frame: ShipFrame;

    fuel: ShipFuel;

    modules: Array<ShipModule>;

    mounts: Array<ShipMount>;

    nav: ShipNav;

    reactor: ShipReactor;

    registration: ShipRegistration;

    /**
     * The globally unique identifier of the ship in the following format: `[AGENT_SYMBOL]_[HEX_ID]`
     */
    symbol: string;

}
