/**
 * This file was generated by st-open-api
 */
import { ShipType } from './ShipType'

/**
 * Open-api schema
 * {
 *   "type": "object",
 *   "properties": {
 *     "type": {
 *       "$ref": "#/components/schemas/ShipType"
 *     }
 *   }
 * }
 */
export interface ShipyardShipTypes {

    type?: ShipType;

}
