/**
 * This file was generated by st-open-api
 */
import { ShipCondition } from './ShipCondition'
import { ShipFrameSymbol } from './ShipFrameSymbol'
import { ShipRequirements } from './ShipRequirements'

/**
 * Open-api schema
 * {
 *   "type": "object",
 *   "description": "The frame of the ship. The frame determines the number of modules and mounting points of the ship, as well as base fuel capacity. As the condition of the frame takes more wear, the ship will become more sluggish and less maneuverable.",
 *   "properties": {
 *     "symbol": {
 *       "type": "string",
 *       "enum": [
 *         "FRAME_PROBE",
 *         "FRAME_DRONE",
 *         "FRAME_INTERCEPTOR",
 *         "FRAME_RACER",
 *         "FRAME_FIGHTER",
 *         "FRAME_FRIGATE",
 *         "FRAME_SHUTTLE",
 *         "FRAME_EXPLORER",
 *         "FRAME_MINER",
 *         "FRAME_LIGHT_FREIGHTER",
 *         "FRAME_HEAVY_FREIGHTER",
 *         "FRAME_TRANSPORT",
 *         "FRAME_DESTROYER",
 *         "FRAME_CRUISER",
 *         "FRAME_CARRIER"
 *       ]
 *     },
 *     "name": {
 *       "type": "string"
 *     },
 *     "description": {
 *       "type": "string"
 *     },
 *     "condition": {
 *       "$ref": "#/components/schemas/ShipCondition"
 *     },
 *     "moduleSlots": {
 *       "type": "integer",
 *       "minimum": 0
 *     },
 *     "mountingPoints": {
 *       "type": "integer",
 *       "minimum": 0
 *     },
 *     "fuelCapacity": {
 *       "type": "integer",
 *       "minimum": 0
 *     },
 *     "requirements": {
 *       "$ref": "#/components/schemas/ShipRequirements"
 *     }
 *   },
 *   "required": [
 *     "symbol",
 *     "name",
 *     "description",
 *     "moduleSlots",
 *     "mountingPoints",
 *     "fuelCapacity",
 *     "requirements"
 *   ]
 * }
 */
export interface ShipFrame {

    condition?: ShipCondition;

    description: string;

    /**
     * open-api validation:
     *   - minimum: 0
     */
    fuelCapacity: number;

    /**
     * open-api validation:
     *   - minimum: 0
     */
    moduleSlots: number;

    /**
     * open-api validation:
     *   - minimum: 0
     */
    mountingPoints: number;

    name: string;

    requirements: ShipRequirements;

    symbol: ShipFrameSymbol;

}
