/**
 * This file was generated by st-open-api
 */

/**
 * Open-api schema
 * {
 *   "type": "object",
 *   "description": "A surveyed deposit of a mineral or resource available for extraction.",
 *   "properties": {
 *     "symbol": {
 *       "type": "string",
 *       "description": "The symbol of the deposit."
 *     }
 *   },
 *   "required": [
 *     "symbol"
 *   ]
 * }
 */
export interface SurveyDeposit {

    /**
     * The symbol of the deposit.
     */
    symbol: string;

}
