/**
 * This file was generated by st-open-api
 */
import { SurveyDeposit } from './SurveyDeposit'
import { SurveySize } from './SurveySize'

/**
 * Open-api schema
 * {
 *   "description": "A resource survey of a waypoint, detailing a specific extraction location and the types of resources that can be found there.",
 *   "type": "object",
 *   "properties": {
 *     "signature": {
 *       "type": "string",
 *       "description": "A unique signature for the location of this survey. This signature is verified when attempting an extraction using this survey.",
 *       "minLength": 1
 *     },
 *     "symbol": {
 *       "type": "string",
 *       "description": "The symbol of the waypoint that this survey is for.",
 *       "minLength": 1
 *     },
 *     "deposits": {
 *       "type": "array",
 *       "description": "A list of deposits that can be found at this location.",
 *       "items": {
 *         "$ref": "#/components/schemas/SurveyDeposit"
 *       }
 *     },
 *     "expiration": {
 *       "type": "string",
 *       "format": "date-time",
 *       "description": "The date and time when the survey expires. After this date and time, the survey will no longer be available for extraction.",
 *       "minimum": 0
 *     },
 *     "size": {
 *       "type": "string",
 *       "description": "The size of the deposit. This value indicates how much can be extracted from the survey before it is exhausted.",
 *       "enum": [
 *         "SMALL",
 *         "MODERATE",
 *         "LARGE"
 *       ]
 *     }
 *   },
 *   "required": [
 *     "signature",
 *     "symbol",
 *     "deposits",
 *     "expiration",
 *     "size"
 *   ]
 * }
 */
export interface Survey {

    /**
     * A list of deposits that can be found at this location.
     */
    deposits: Array<SurveyDeposit>;

    /**
     * The date and time when the survey expires. After this date and time, the survey will no longer be available for extraction.
     * open-api format: date-time
     * open-api validation:
     *   - minimum: 0
     */
    expiration: Date;

    /**
     * A unique signature for the location of this survey. This signature is verified when attempting an extraction using this survey.
     * open-api validation:
     *   - minLength: 1
     */
    signature: string;

    /**
     * The size of the deposit. This value indicates how much can be extracted from the survey before it is exhausted.
     */
    size: SurveySize;

    /**
     * The symbol of the waypoint that this survey is for.
     * open-api validation:
     *   - minLength: 1
     */
    symbol: string;

}
