/**
 * This file was generated by st-open-api
 */
import { SystemFaction } from './SystemFaction'
import { SystemType } from './SystemType'
import { SystemWaypoint } from './SystemWaypoint'

/**
 * Open-api schema
 * {
 *   "description": "",
 *   "type": "object",
 *   "properties": {
 *     "symbol": {
 *       "type": "string",
 *       "minLength": 1
 *     },
 *     "sectorSymbol": {
 *       "type": "string",
 *       "minLength": 1
 *     },
 *     "type": {
 *       "$ref": "#/components/schemas/SystemType"
 *     },
 *     "x": {
 *       "type": "integer"
 *     },
 *     "y": {
 *       "type": "integer"
 *     },
 *     "waypoints": {
 *       "type": "array",
 *       "items": {
 *         "$ref": "#/components/schemas/SystemWaypoint"
 *       }
 *     },
 *     "factions": {
 *       "type": "array",
 *       "items": {
 *         "$ref": "#/components/schemas/SystemFaction"
 *       }
 *     }
 *   },
 *   "required": [
 *     "symbol",
 *     "sectorSymbol",
 *     "type",
 *     "x",
 *     "y",
 *     "waypoints",
 *     "factions"
 *   ]
 * }
 */
export interface System {

    factions: Array<SystemFaction>;

    /**
     * open-api validation:
     *   - minLength: 1
     */
    sectorSymbol: string;

    /**
     * open-api validation:
     *   - minLength: 1
     */
    symbol: string;

    type: SystemType;

    waypoints: Array<SystemWaypoint>;

    x: number;

    y: number;

}
