/**
 * This file was generated by st-open-api
 */
import { TradeSymbol } from './TradeSymbol'

/**
 * Open-api schema
 * {
 *   "type": "object",
 *   "properties": {
 *     "symbol": {
 *       "$ref": "#/components/schemas/TradeSymbol"
 *     },
 *     "name": {
 *       "type": "string"
 *     },
 *     "description": {
 *       "type": "string"
 *     }
 *   },
 *   "required": [
 *     "symbol",
 *     "name",
 *     "description"
 *   ]
 * }
 */
export interface TradeGood {

    description: string;

    name: string;

    symbol: TradeSymbol;

}
