/**
 * This file was generated by st-open-api
 */

/**
 * Open-api schema
 * {
 *   "type": "object",
 *   "properties": {
 *     "symbol": {
 *       "type": "string",
 *       "minLength": 1
 *     }
 *   },
 *   "required": [
 *     "symbol"
 *   ]
 * }
 */
export interface WaypointFaction {

    /**
     * open-api validation:
     *   - minLength: 1
     */
    symbol: string;

}
