/**
 * This file was generated by st-open-api
 */

/**
 * Open-api schema
 * {
 *   "type": "object",
 *   "required": [
 *     "contractId"
 *   ],
 *   "properties": {
 *     "contractId": {
 *       "type": "string"
 *     }
 *   }
 * }
 */
export interface GetContractPathParameter {

    contractId: string;

}
