/**
 * This file was generated by st-open-api
 */

/**
 * Open-api schema
 * {
 *   "type": "object",
 *   "required": [
 *     "factionSymbol"
 *   ],
 *   "properties": {
 *     "factionSymbol": {
 *       "default": "CGR",
 *       "type": "string"
 *     }
 *   }
 * }
 */
export interface GetFactionPathParameter {

    factionSymbol: string;

}
