/**
 * This file was generated by st-open-api
 */

/**
 * Open-api schema
 * {
 *   "type": "object",
 *   "required": [
 *     "systemSymbol"
 *   ],
 *   "properties": {
 *     "systemSymbol": {
 *       "type": "string"
 *     }
 *   }
 * }
 */
export interface GetSystemWaypointsPathParameter {

    systemSymbol: string;

}
