/**
 * This file was generated by st-open-api
 */

/**
 * Open-api schema
 * {
 *   "type": "object",
 *   "required": [],
 *   "properties": {
 *     "page": {
 *       "type": "integer",
 *       "minimum": 1
 *     },
 *     "limit": {
 *       "type": "integer",
 *       "minimum": 1,
 *       "maximum": 20
 *     }
 *   }
 * }
 */
export interface GetSystemsQueryParameter {

    /**
     * open-api validation:
     *   - minimum: 1
     *   - maximum: 20
     */
    limit?: number;

    /**
     * open-api validation:
     *   - minimum: 1
     */
    page?: number;

}
