/**
 * This file was generated by st-open-api
 */

/**
 * Open-api schema
 * {
 *   "type": "object",
 *   "required": [
 *     "systemSymbol",
 *     "waypointSymbol"
 *   ],
 *   "properties": {
 *     "systemSymbol": {
 *       "type": "string"
 *     },
 *     "waypointSymbol": {
 *       "type": "string"
 *     }
 *   }
 * }
 */
export interface GetShipyardPathParameter {

    systemSymbol: string;

    waypointSymbol: string;

}
