/**
 * This file was generated by st-open-api
 */
import { CreateSurveyResponseData } from './CreateSurveyResponseData'

/**
 * Open-api schema
 * {
 *   "properties": {
 *     "data": {
 *       "properties": {
 *         "cooldown": {
 *           "$ref": "#/components/schemas/Cooldown"
 *         },
 *         "surveys": {
 *           "items": {
 *             "$ref": "#/components/schemas/Survey"
 *           },
 *           "type": "array"
 *         }
 *       },
 *       "required": [
 *         "surveys",
 *         "cooldown"
 *       ],
 *       "type": "object"
 *     }
 *   },
 *   "type": "object",
 *   "required": [
 *     "data"
 *   ]
 * }
 */
export interface CreateSurveyResponse {

    data: CreateSurveyResponseData;

}
