/**
 * This file was generated by st-open-api
 */
import { Cooldown } from '../components/Cooldown'
import { ScannedSystem } from '../components/ScannedSystem'

/**
 * Open-api schema
 * {
 *   "properties": {
 *     "cooldown": {
 *       "$ref": "#/components/schemas/Cooldown"
 *     },
 *     "systems": {
 *       "items": {
 *         "$ref": "#/components/schemas/ScannedSystem"
 *       },
 *       "type": "array"
 *     }
 *   },
 *   "required": [
 *     "cooldown",
 *     "systems"
 *   ],
 *   "type": "object"
 * }
 */
export interface CreateShipSystemScanResponseData {

    cooldown: Cooldown;

    systems: Array<ScannedSystem>;

}
