/**
 * This file was generated by st-open-api
 */
import { Cooldown } from '../components/Cooldown'
import { Survey } from '../components/Survey'

/**
 * Open-api schema
 * {
 *   "properties": {
 *     "cooldown": {
 *       "$ref": "#/components/schemas/Cooldown"
 *     },
 *     "surveys": {
 *       "items": {
 *         "$ref": "#/components/schemas/Survey"
 *       },
 *       "type": "array"
 *     }
 *   },
 *   "required": [
 *     "surveys",
 *     "cooldown"
 *   ],
 *   "type": "object"
 * }
 */
export interface CreateSurveyResponseData {

    cooldown: Cooldown;

    surveys: Array<Survey>;

}
