/**
 * This file was generated by st-open-api
 */
import { Cooldown } from '../components/Cooldown'
import { ScannedShip } from '../components/ScannedShip'

/**
 * Open-api schema
 * {
 *   "properties": {
 *     "cooldown": {
 *       "$ref": "#/components/schemas/Cooldown"
 *     },
 *     "ships": {
 *       "items": {
 *         "$ref": "#/components/schemas/ScannedShip"
 *       },
 *       "type": "array"
 *     }
 *   },
 *   "required": [
 *     "cooldown",
 *     "ships"
 *   ],
 *   "type": "object"
 * }
 */
export interface CreateShipShipScanResponseData {

    cooldown: Cooldown;

    ships: Array<ScannedShip>;

}
