/**
 * This file was generated by st-open-api
 */
import { Cooldown } from '../components/Cooldown'
import { ScannedWaypoint } from '../components/ScannedWaypoint'

/**
 * Open-api schema
 * {
 *   "properties": {
 *     "cooldown": {
 *       "$ref": "#/components/schemas/Cooldown"
 *     },
 *     "waypoints": {
 *       "items": {
 *         "$ref": "#/components/schemas/ScannedWaypoint"
 *       },
 *       "type": "array"
 *     }
 *   },
 *   "required": [
 *     "cooldown",
 *     "waypoints"
 *   ],
 *   "type": "object"
 * }
 */
export interface CreateShipWaypointScanResponseData {

    cooldown: Cooldown;

    waypoints: Array<ScannedWaypoint>;

}
