/**
 * This file was generated by st-open-api
 */
import { Chart } from '../components/Chart'
import { Waypoint } from '../components/Waypoint'

/**
 * Open-api schema
 * {
 *   "properties": {
 *     "chart": {
 *       "$ref": "#/components/schemas/Chart"
 *     },
 *     "waypoint": {
 *       "$ref": "#/components/schemas/Waypoint"
 *     }
 *   },
 *   "required": [
 *     "chart",
 *     "waypoint"
 *   ],
 *   "type": "object"
 * }
 */
export interface CreateChartResponseData {

    chart: Chart;

    waypoint: Waypoint;

}
