/**
 * This file was generated by st-open-api
 */
import { Contract } from '../components/Contract'
import { ShipCargo } from '../components/ShipCargo'

/**
 * Open-api schema
 * {
 *   "properties": {
 *     "contract": {
 *       "$ref": "#/components/schemas/Contract"
 *     },
 *     "cargo": {
 *       "$ref": "#/components/schemas/ShipCargo"
 *     }
 *   },
 *   "required": [
 *     "contract",
 *     "cargo"
 *   ],
 *   "type": "object"
 * }
 */
export interface DeliverContractResponseData {

    cargo: ShipCargo;

    contract: Contract;

}
