/**
 * This file was generated by st-open-api
 */
import { ExtractResourcesResponseData } from './ExtractResourcesResponseData'

/**
 * Open-api schema
 * {
 *   "description": "",
 *   "properties": {
 *     "data": {
 *       "properties": {
 *         "cooldown": {
 *           "$ref": "#/components/schemas/Cooldown"
 *         },
 *         "extraction": {
 *           "$ref": "#/components/schemas/Extraction"
 *         },
 *         "cargo": {
 *           "$ref": "#/components/schemas/ShipCargo"
 *         }
 *       },
 *       "required": [
 *         "extraction",
 *         "cooldown",
 *         "cargo"
 *       ],
 *       "type": "object"
 *     }
 *   },
 *   "required": [
 *     "data"
 *   ],
 *   "type": "object"
 * }
 */
export interface ExtractResourcesResponse {

    data: ExtractResourcesResponseData;

}
