/**
 * This file was generated by st-open-api
 */
import { Cooldown } from '../components/Cooldown'
import { Extraction } from '../components/Extraction'
import { ShipCargo } from '../components/ShipCargo'

/**
 * Open-api schema
 * {
 *   "properties": {
 *     "cooldown": {
 *       "$ref": "#/components/schemas/Cooldown"
 *     },
 *     "extraction": {
 *       "$ref": "#/components/schemas/Extraction"
 *     },
 *     "cargo": {
 *       "$ref": "#/components/schemas/ShipCargo"
 *     }
 *   },
 *   "required": [
 *     "extraction",
 *     "cooldown",
 *     "cargo"
 *   ],
 *   "type": "object"
 * }
 */
export interface ExtractResourcesResponseData {

    cargo: ShipCargo;

    cooldown: Cooldown;

    extraction: Extraction;

}
