/**
 * This file was generated by st-open-api
 */
import { Agent } from '../components/Agent'
import { Contract } from '../components/Contract'

/**
 * Open-api schema
 * {
 *   "properties": {
 *     "agent": {
 *       "$ref": "#/components/schemas/Agent"
 *     },
 *     "contract": {
 *       "$ref": "#/components/schemas/Contract"
 *     }
 *   },
 *   "required": [
 *     "contract",
 *     "agent"
 *   ],
 *   "type": "object"
 * }
 */
export interface FulfillContractResponseData {

    agent: Agent;

    contract: Contract;

}
