/**
 * This file was generated by st-open-api
 */
import { Contract } from '../components/Contract'

/**
 * Open-api schema
 * {
 *   "properties": {
 *     "data": {
 *       "$ref": "#/components/schemas/Contract"
 *     }
 *   },
 *   "required": [
 *     "data"
 *   ],
 *   "type": "object"
 * }
 */
export interface GetContractResponse {

    data: Contract;

}
