/**
 * This file was generated by st-open-api
 */
import { Contract } from '../components/Contract'
import { Meta } from '../components/Meta'

/**
 * Open-api schema
 * {
 *   "description": "",
 *   "properties": {
 *     "data": {
 *       "items": {
 *         "$ref": "#/components/schemas/Contract"
 *       },
 *       "type": "array"
 *     },
 *     "meta": {
 *       "$ref": "#/components/schemas/Meta"
 *     }
 *   },
 *   "required": [
 *     "data",
 *     "meta"
 *   ],
 *   "type": "object"
 * }
 */
export interface GetContractsResponse {

    data: Array<Contract>;

    meta: Meta;

}
