/**
 * This file was generated by st-open-api
 */
import { Faction } from '../components/Faction'

/**
 * Open-api schema
 * {
 *   "properties": {
 *     "data": {
 *       "$ref": "#/components/schemas/Faction"
 *     }
 *   },
 *   "required": [
 *     "data"
 *   ],
 *   "type": "object"
 * }
 */
export interface GetFactionResponse {

    data: Faction;

}
