/**
 * This file was generated by st-open-api
 */
import { JumpGate } from '../components/JumpGate'

/**
 * Open-api schema
 * {
 *   "description": "",
 *   "properties": {
 *     "data": {
 *       "$ref": "#/components/schemas/JumpGate"
 *     }
 *   },
 *   "required": [
 *     "data"
 *   ],
 *   "type": "object"
 * }
 */
export interface GetJumpGateResponse {

    data: JumpGate;

}
