/**
 * This file was generated by st-open-api
 */
import { Agent } from '../components/Agent'

/**
 * Open-api schema
 * {
 *   "properties": {
 *     "data": {
 *       "$ref": "#/components/schemas/Agent"
 *     }
 *   },
 *   "required": [
 *     "data"
 *   ],
 *   "type": "object"
 * }
 */
export interface GetMyAgentResponse {

    data: Agent;

}
