/**
 * This file was generated by st-open-api
 */
import { Ship } from '../components/Ship'

/**
 * Open-api schema
 * {
 *   "description": "",
 *   "properties": {
 *     "data": {
 *       "$ref": "#/components/schemas/Ship"
 *     }
 *   },
 *   "required": [
 *     "data"
 *   ],
 *   "type": "object"
 * }
 */
export interface GetMyShipResponse {

    data: Ship;

}
