/**
 * This file was generated by st-open-api
 */
import { Market } from '../components/Market'

/**
 * Open-api schema
 * {
 *   "properties": {
 *     "data": {
 *       "$ref": "#/components/schemas/Market"
 *     }
 *   },
 *   "required": [
 *     "data"
 *   ],
 *   "type": "object"
 * }
 */
export interface GetMarketResponse {

    data: Market;

}
