/**
 * This file was generated by st-open-api
 */
import { ShipCargo } from '../components/ShipCargo'

/**
 * Open-api schema
 * {
 *   "description": "",
 *   "properties": {
 *     "data": {
 *       "$ref": "#/components/schemas/ShipCargo"
 *     }
 *   },
 *   "required": [
 *     "data"
 *   ],
 *   "type": "object"
 * }
 */
export interface GetMyShipCargoResponse {

    data: ShipCargo;

}
