/**
 * This file was generated by st-open-api
 */
import { Shipyard } from '../components/Shipyard'

/**
 * Open-api schema
 * {
 *   "description": "",
 *   "properties": {
 *     "data": {
 *       "$ref": "#/components/schemas/Shipyard"
 *     }
 *   },
 *   "required": [
 *     "data"
 *   ],
 *   "type": "object"
 * }
 */
export interface GetShipyardResponse {

    data: Shipyard;

}
