/**
 * This file was generated by st-open-api
 */
import { Cooldown } from '../components/Cooldown'

/**
 * Open-api schema
 * {
 *   "description": "",
 *   "properties": {
 *     "data": {
 *       "$ref": "#/components/schemas/Cooldown"
 *     }
 *   },
 *   "required": [
 *     "data"
 *   ],
 *   "type": "object"
 * }
 */
export interface GetShipCooldownResponse {

    data: Cooldown;

}
