/**
 * This file was generated by st-open-api
 */
import { Meta } from '../components/Meta'
import { Waypoint } from '../components/Waypoint'

/**
 * Open-api schema
 * {
 *   "description": "",
 *   "properties": {
 *     "data": {
 *       "items": {
 *         "$ref": "#/components/schemas/Waypoint"
 *       },
 *       "type": "array"
 *     },
 *     "meta": {
 *       "$ref": "#/components/schemas/Meta"
 *     }
 *   },
 *   "required": [
 *     "data",
 *     "meta"
 *   ],
 *   "type": "object"
 * }
 */
export interface GetSystemWaypointsResponse {

    data: Array<Waypoint>;

    meta: Meta;

}
