/**
 * This file was generated by st-open-api
 */
import { Waypoint } from '../components/Waypoint'

/**
 * Open-api schema
 * {
 *   "description": "",
 *   "properties": {
 *     "data": {
 *       "$ref": "#/components/schemas/Waypoint"
 *     }
 *   },
 *   "required": [
 *     "data"
 *   ],
 *   "type": "object"
 * }
 */
export interface GetWaypointResponse {

    data: Waypoint;

}
