/**
 * This file was generated by st-open-api
 */
import {IDataAcceptContractResponse} from './interface/i-data-accept-contract-response';

export interface IAcceptContractResponse {

    data: IDataAcceptContractResponse;

}
