/**
 * This file was generated by st-open-api
 */
import {IDataCreateShipWaypointScanResponse} from './interface/i-data-create-ship-waypoint-scan-response';

export interface ICreateShipWaypointScanResponse {

    data: IDataCreateShipWaypointScanResponse;

}
