/**
 * This file was generated by st-open-api
 */
import {IDataCreateShipSystemScanResponse} from './interface/i-data-create-ship-system-scan-response';

export interface ICreateShipSystemScanResponse {

    data: IDataCreateShipSystemScanResponse;

}
