/**
 * This file was generated by st-open-api
 */
import {IDataCreateChartResponse} from './interface/i-data-create-chart-response';

export interface ICreateChartResponse {

    data: IDataCreateChartResponse;

}
