/**
 * This file was generated by st-open-api
 */
import {IDataCreateShipShipScanResponse} from './interface/i-data-create-ship-ship-scan-response';

export interface ICreateShipShipScanResponse {

    data: IDataCreateShipShipScanResponse;

}
