/**
 * This file was generated by st-open-api
 */
import {IDataCreateSurveyResponse} from './interface/i-data-create-survey-response';

export interface ICreateSurveyResponse {

    data: IDataCreateSurveyResponse;

}
