/**
 * This file was generated by st-open-api
 */
import {IDataDeliverContractResponse} from './interface/i-data-deliver-contract-response';

export interface IDeliverContractResponse {

    data: IDataDeliverContractResponse;

}
