/**
 * This file was generated by st-open-api
 */
import {IDataDockShipResponse} from './interface/i-data-dock-ship-response';

export interface IDockShipResponse {

    data: IDataDockShipResponse;

}
