/**
 * This file was generated by st-open-api
 */
import {IDataExtractResourcesResponse} from './interface/i-data-extract-resources-response';

export interface IExtractResourcesResponse {

    data: IDataExtractResourcesResponse;

}
