/**
 * This file was generated by st-open-api
 */
import {IDataFulfillContractResponse} from './interface/i-data-fulfill-contract-response';

export interface IFulfillContractResponse {

    data: IDataFulfillContractResponse;

}
