/**
 * This file was generated by st-open-api
 */
import {IDataJettisonResponse} from './interface/i-data-jettison-response';

export interface IJettisonResponse {

    data: IDataJettisonResponse;

}
