/**
 * This file was generated by st-open-api
 */
import {IDataJumpShipResponse} from './interface/i-data-jump-ship-response';

export interface IJumpShipResponse {

    data: IDataJumpShipResponse;

}
