/**
 * This file was generated by st-open-api
 */
import {IDataNavigateShipResponse} from './interface/i-data-navigate-ship-response';

export interface INavigateShipResponse {

    data: IDataNavigateShipResponse;

}
