/**
 * This file was generated by st-open-api
 */
import {IDataOrbitShipResponse} from './interface/i-data-orbit-ship-response';

export interface IOrbitShipResponse {

    data: IDataOrbitShipResponse;

}
