/**
 * This file was generated by st-open-api
 */
import {IDataPurchaseShipResponse} from './interface/i-data-purchase-ship-response';

export interface IPurchaseShipResponse {

    data: IDataPurchaseShipResponse;

}
