/**
 * This file was generated by st-open-api
 */
import {IDataPurchaseCargoResponse} from './interface/i-data-purchase-cargo-response';

export interface IPurchaseCargoResponse {

    data: IDataPurchaseCargoResponse;

}
