/**
 * This file was generated by st-open-api
 */
import {IDataRegisterResponse} from './interface/i-data-register-response';

export interface IRegisterResponse {

    data: IDataRegisterResponse;

}
