/**
 * This file was generated by st-open-api
 */
import {IDataRefuelShipResponse} from './interface/i-data-refuel-ship-response';

export interface IRefuelShipResponse {

    data: IDataRefuelShipResponse;

}
