/**
 * This file was generated by st-open-api
 */
import {IDataSellCargoResponse} from './interface/i-data-sell-cargo-response';

export interface ISellCargoResponse {

    data: IDataSellCargoResponse;

}
