/**
 * This file was generated by st-open-api
 */
import {IDataShipRefineResponse} from './interface/i-data-ship-refine-response';

export interface IShipRefineResponse {

    data: IDataShipRefineResponse;

}
