/**
 * This file was generated by st-open-api
 */
import {IDataTransferCargoResponse} from './interface/i-data-transfer-cargo-response';

export interface ITransferCargoResponse {

    data: IDataTransferCargoResponse;

}
