/**
 * This file was generated by st-open-api
 */
import {IDataWarpShipResponse} from './interface/i-data-warp-ship-response';

export interface IWarpShipResponse {

    data: IDataWarpShipResponse;

}
