/**
 * This file was generated by st-open-api
 */
import { JettisonResponseData } from './JettisonResponseData'

/**
 * Open-api schema
 * {
 *   "description": "",
 *   "properties": {
 *     "data": {
 *       "properties": {
 *         "cargo": {
 *           "$ref": "#/components/schemas/ShipCargo"
 *         }
 *       },
 *       "required": [
 *         "cargo"
 *       ],
 *       "type": "object"
 *     }
 *   },
 *   "required": [
 *     "data"
 *   ],
 *   "type": "object"
 * }
 */
export interface JettisonResponse {

    data: JettisonResponseData;

}
