/**
 * This file was generated by st-open-api
 */
import { Cooldown } from '../components/Cooldown'
import { ShipNav } from '../components/ShipNav'

/**
 * Open-api schema
 * {
 *   "properties": {
 *     "cooldown": {
 *       "$ref": "#/components/schemas/Cooldown"
 *     },
 *     "nav": {
 *       "$ref": "#/components/schemas/ShipNav"
 *     }
 *   },
 *   "required": [
 *     "route",
 *     "cooldown"
 *   ],
 *   "type": "object"
 * }
 */
export interface JumpShipResponseData {

    cooldown: Cooldown;

    nav?: ShipNav;

}
