/**
 * This file was generated by st-open-api
 */
import { JumpShipResponseData } from './JumpShipResponseData'

/**
 * Open-api schema
 * {
 *   "description": "",
 *   "properties": {
 *     "data": {
 *       "properties": {
 *         "cooldown": {
 *           "$ref": "#/components/schemas/Cooldown"
 *         },
 *         "nav": {
 *           "$ref": "#/components/schemas/ShipNav"
 *         }
 *       },
 *       "required": [
 *         "route",
 *         "cooldown"
 *       ],
 *       "type": "object"
 *     }
 *   },
 *   "required": [
 *     "data"
 *   ],
 *   "type": "object"
 * }
 */
export interface JumpShipResponse {

    data: JumpShipResponseData;

}
