/**
 * This file was generated by st-open-api
 */
import { NavigateShipResponseData } from './NavigateShipResponseData'

/**
 * Open-api schema
 * {
 *   "description": "",
 *   "properties": {
 *     "data": {
 *       "properties": {
 *         "fuel": {
 *           "$ref": "#/components/schemas/ShipFuel"
 *         },
 *         "nav": {
 *           "$ref": "#/components/schemas/ShipNav"
 *         }
 *       },
 *       "required": [
 *         "nav",
 *         "fuel"
 *       ],
 *       "type": "object"
 *     }
 *   },
 *   "required": [
 *     "data"
 *   ],
 *   "type": "object"
 * }
 */
export interface NavigateShipResponse {

    data: NavigateShipResponseData;

}
