/**
 * This file was generated by st-open-api
 */
import { OrbitShipResponseData } from './OrbitShipResponseData'

/**
 * Open-api schema
 * {
 *   "title": "Orbit Ship 200 Response",
 *   "description": "",
 *   "properties": {
 *     "data": {
 *       "properties": {
 *         "nav": {
 *           "$ref": "#/components/schemas/ShipNav"
 *         }
 *       },
 *       "type": "object",
 *       "required": [
 *         "nav"
 *       ]
 *     }
 *   },
 *   "required": [
 *     "data"
 *   ],
 *   "type": "object"
 * }
 */
export interface OrbitShipResponse {

    data: OrbitShipResponseData;

}
