/**
 * This file was generated by st-open-api
 */
import { ShipNav } from '../components/ShipNav'

/**
 * Open-api schema
 * {
 *   "properties": {
 *     "nav": {
 *       "$ref": "#/components/schemas/ShipNav"
 *     }
 *   },
 *   "type": "object",
 *   "required": [
 *     "nav"
 *   ]
 * }
 */
export interface OrbitShipResponseData {

    nav: ShipNav;

}
