/**
 * This file was generated by st-open-api
 */
import { ShipNav } from '../components/ShipNav'

/**
 * Open-api schema
 * {
 *   "description": "",
 *   "properties": {
 *     "data": {
 *       "$ref": "#/components/schemas/ShipNav"
 *     }
 *   },
 *   "required": [
 *     "data"
 *   ],
 *   "type": "object"
 * }
 */
export interface PatchShipNavResponse {

    data: ShipNav;

}
