/**
 * This file was generated by st-open-api
 */
import { PurchaseCargoResponseData } from './PurchaseCargoResponseData'

/**
 * Open-api schema
 * {
 *   "title": "Purchase Cargo 201 Response",
 *   "description": "",
 *   "properties": {
 *     "data": {
 *       "properties": {
 *         "agent": {
 *           "$ref": "#/components/schemas/Agent"
 *         },
 *         "cargo": {
 *           "$ref": "#/components/schemas/ShipCargo"
 *         },
 *         "transaction": {
 *           "$ref": "#/components/schemas/MarketTransaction"
 *         }
 *       },
 *       "required": [
 *         "cargo",
 *         "transaction",
 *         "agent"
 *       ],
 *       "type": "object"
 *     }
 *   },
 *   "required": [
 *     "data"
 *   ],
 *   "type": "object"
 * }
 */
export interface PurchaseCargoResponse {

    data: PurchaseCargoResponseData;

}
