/**
 * This file was generated by st-open-api
 */
import { PurchaseShipResponseData } from './PurchaseShipResponseData'

/**
 * Open-api schema
 * {
 *   "description": "",
 *   "properties": {
 *     "data": {
 *       "properties": {
 *         "agent": {
 *           "$ref": "#/components/schemas/Agent"
 *         },
 *         "ship": {
 *           "$ref": "#/components/schemas/Ship"
 *         },
 *         "transaction": {
 *           "$ref": "#/components/schemas/ShipyardTransaction"
 *         }
 *       },
 *       "required": [
 *         "ship",
 *         "agent",
 *         "transaction"
 *       ],
 *       "type": "object"
 *     }
 *   },
 *   "required": [
 *     "data"
 *   ],
 *   "type": "object"
 * }
 */
export interface PurchaseShipResponse {

    data: PurchaseShipResponseData;

}
