/**
 * This file was generated by st-open-api
 */
import { RefuelShipResponseData } from './RefuelShipResponseData'

/**
 * Open-api schema
 * {
 *   "description": "",
 *   "properties": {
 *     "data": {
 *       "properties": {
 *         "agent": {
 *           "$ref": "#/components/schemas/Agent"
 *         },
 *         "fuel": {
 *           "$ref": "#/components/schemas/ShipFuel"
 *         }
 *       },
 *       "required": [
 *         "agent",
 *         "fuel"
 *       ],
 *       "type": "object"
 *     }
 *   },
 *   "required": [
 *     "data"
 *   ],
 *   "type": "object"
 * }
 */
export interface RefuelShipResponse {

    data: RefuelShipResponseData;

}
