/**
 * This file was generated by st-open-api
 */
import { Agent } from '../components/Agent'
import { ShipFuel } from '../components/ShipFuel'

/**
 * Open-api schema
 * {
 *   "properties": {
 *     "agent": {
 *       "$ref": "#/components/schemas/Agent"
 *     },
 *     "fuel": {
 *       "$ref": "#/components/schemas/ShipFuel"
 *     }
 *   },
 *   "required": [
 *     "agent",
 *     "fuel"
 *   ],
 *   "type": "object"
 * }
 */
export interface RefuelShipResponseData {

    agent: Agent;

    fuel: ShipFuel;

}
