/**
 * This file was generated by st-open-api
 */
import { RegisterResponseData } from './RegisterResponseData'

/**
 * Open-api schema
 * {
 *   "properties": {
 *     "data": {
 *       "properties": {
 *         "agent": {
 *           "$ref": "#/components/schemas/Agent"
 *         },
 *         "contract": {
 *           "$ref": "#/components/schemas/Contract"
 *         },
 *         "faction": {
 *           "$ref": "#/components/schemas/Faction"
 *         },
 *         "ship": {
 *           "$ref": "#/components/schemas/Ship"
 *         },
 *         "token": {
 *           "description": "A Bearer token for accessing secured API endpoints.",
 *           "type": "string"
 *         }
 *       },
 *       "required": [
 *         "token",
 *         "agent",
 *         "faction",
 *         "contract",
 *         "ship"
 *       ],
 *       "type": "object"
 *     }
 *   },
 *   "required": [
 *     "data"
 *   ],
 *   "type": "object"
 * }
 */
export interface RegisterResponse {

    data: RegisterResponseData;

}
