/**
 * This file was generated by st-open-api
 */
import { Agent } from '../components/Agent'
import { MarketTransaction } from '../components/MarketTransaction'
import { ShipCargo } from '../components/ShipCargo'

/**
 * Open-api schema
 * {
 *   "properties": {
 *     "agent": {
 *       "$ref": "#/components/schemas/Agent"
 *     },
 *     "cargo": {
 *       "$ref": "#/components/schemas/ShipCargo"
 *     },
 *     "transaction": {
 *       "$ref": "#/components/schemas/MarketTransaction"
 *     }
 *   },
 *   "required": [
 *     "cargo",
 *     "transaction",
 *     "agent"
 *   ],
 *   "type": "object"
 * }
 */
export interface SellCargoResponseData {

    agent: Agent;

    cargo: ShipCargo;

    transaction: MarketTransaction;

}
