/**
 * This file was generated by st-open-api
 */
import { ShipRefineResponseData } from './ShipRefineResponseData'

/**
 * Open-api schema
 * {
 *   "title": "Ship Refine 200 Response",
 *   "description": "",
 *   "properties": {
 *     "data": {
 *       "properties": {
 *         "cargo": {
 *           "$ref": "#/components/schemas/ShipCargo"
 *         },
 *         "cooldown": {
 *           "$ref": "#/components/schemas/Cooldown"
 *         },
 *         "produced": {
 *           "type": "array",
 *           "items": {
 *             "type": "object",
 *             "properties": {
 *               "tradeSymbol": {
 *                 "type": "string"
 *               },
 *               "units": {
 *                 "type": "integer"
 *               }
 *             }
 *           }
 *         },
 *         "consumed": {
 *           "type": "array",
 *           "items": {
 *             "type": "object",
 *             "properties": {
 *               "tradeSymbol": {
 *                 "type": "string"
 *               },
 *               "units": {
 *                 "type": "integer"
 *               }
 *             }
 *           }
 *         }
 *       },
 *       "type": "object",
 *       "required": [
 *         "cargo",
 *         "cooldown",
 *         "produced",
 *         "consumed"
 *       ]
 *     }
 *   },
 *   "required": [
 *     "data"
 *   ],
 *   "type": "object"
 * }
 */
export interface ShipRefineResponse {

    data: ShipRefineResponseData;

}
