/**
 * This file was generated by st-open-api
 */

/**
 * Open-api schema
 * {
 *   "type": "object",
 *   "properties": {
 *     "tradeSymbol": {
 *       "type": "string"
 *     },
 *     "units": {
 *       "type": "integer"
 *     }
 *   }
 * }
 */
export interface ShipRefineResponseDataConsumed {

    tradeSymbol?: string;

    units?: number;

}
