/**
 * This file was generated by st-open-api
 */
import { Cooldown } from '../components/Cooldown'
import { ShipCargo } from '../components/ShipCargo'
import { ShipRefineResponseDataConsumed } from './ShipRefineResponseDataConsumed'
import { ShipRefineResponseDataProduced } from './ShipRefineResponseDataProduced'

/**
 * Open-api schema
 * {
 *   "properties": {
 *     "cargo": {
 *       "$ref": "#/components/schemas/ShipCargo"
 *     },
 *     "cooldown": {
 *       "$ref": "#/components/schemas/Cooldown"
 *     },
 *     "produced": {
 *       "type": "array",
 *       "items": {
 *         "type": "object",
 *         "properties": {
 *           "tradeSymbol": {
 *             "type": "string"
 *           },
 *           "units": {
 *             "type": "integer"
 *           }
 *         }
 *       }
 *     },
 *     "consumed": {
 *       "type": "array",
 *       "items": {
 *         "type": "object",
 *         "properties": {
 *           "tradeSymbol": {
 *             "type": "string"
 *           },
 *           "units": {
 *             "type": "integer"
 *           }
 *         }
 *       }
 *     }
 *   },
 *   "type": "object",
 *   "required": [
 *     "cargo",
 *     "cooldown",
 *     "produced",
 *     "consumed"
 *   ]
 * }
 */
export interface ShipRefineResponseData {

    cargo: ShipCargo;

    consumed: Array<ShipRefineResponseDataConsumed>;

    cooldown: Cooldown;

    produced: Array<ShipRefineResponseDataProduced>;

}
