/**
 * This file was generated by st-open-api
 */
import { Survey } from '../components/Survey'

/**
 * Open-api schema
 * {
 *   "properties": {
 *     "survey": {
 *       "$ref": "#/components/schemas/Survey"
 *     }
 *   },
 *   "type": "object"
 * }
 */
export interface ExtractResourcesRequest {

    survey?: Survey;

}
