/**
 * This file was generated by st-open-api
 */
import {IShipNavFlightMode} from '../components/i-ship-nav-flight-mode';

export interface IPatchShipNavRequest {

    flightMode?: IShipNavFlightMode;

}
