/**
 * This file was generated by st-open-api
 */
import {IShipType} from '../components/i-ship-type';

export interface IPurchaseShipRequest {

    shipType: IShipType;

    waypointSymbol: string;

}
