/**
 * This file was generated by st-open-api
 */
import {IFactionRegisterRequest} from './enumeration/i-faction-register-request';

export interface IRegisterRequest {

    faction: IFactionRegisterRequest;

    symbol: string;

}
