/**
 * This file was generated by st-open-api
 */
import {IProduceShipRefineRequest} from './enumeration/i-produce-ship-refine-request';

export interface IShipRefineRequest {

    produce: IProduceShipRefineRequest;

}
