/**
 * This file was generated by st-open-api
 */

/**
 * Open-api schema
 * {
 *   "properties": {
 *     "symbol": {
 *       "type": "string"
 *     },
 *     "units": {
 *       "minimum": 1,
 *       "type": "integer"
 *     }
 *   },
 *   "required": [
 *     "symbol",
 *     "units"
 *   ],
 *   "type": "object"
 * }
 */
export interface JettisonRequest {

    symbol: string;

    /**
     * open-api validation:
     *   - minimum: 1
     */
    units: number;

}
