/**
 * This file was generated by st-open-api
 */

/**
 * Open-api schema
 * {
 *   "properties": {
 *     "systemSymbol": {
 *       "description": "The system symbol to jump to.",
 *       "type": "string"
 *     }
 *   },
 *   "required": [
 *     "systemSymbol"
 *   ],
 *   "type": "object"
 * }
 */
export interface JumpShipRequest {

    /**
     * The system symbol to jump to.
     */
    systemSymbol: string;

}
