/**
 * This file was generated by st-open-api
 */

/**
 * Open-api schema
 * {
 *   "properties": {
 *     "waypointSymbol": {
 *       "description": "The target destination.",
 *       "type": "string"
 *     }
 *   },
 *   "required": [
 *     "waypointSymbol"
 *   ],
 *   "type": "object"
 * }
 */
export interface NavigateShipRequest {

    /**
     * The target destination.
     */
    waypointSymbol: string;

}
