/**
 * This file was generated by st-open-api
 */
import { ShipNavFlightMode } from '../components/ShipNavFlightMode'

/**
 * Open-api schema
 * {
 *   "properties": {
 *     "flightMode": {
 *       "$ref": "#/components/schemas/ShipNavFlightMode"
 *     }
 *   },
 *   "type": "object"
 * }
 */
export interface PatchShipNavRequest {

    flightMode?: ShipNavFlightMode;

}
