/**
 * This file was generated by st-open-api
 */
import { ShipType } from '../components/ShipType'

/**
 * Open-api schema
 * {
 *   "properties": {
 *     "shipType": {
 *       "$ref": "#/components/schemas/ShipType"
 *     },
 *     "waypointSymbol": {
 *       "description": "The symbol of the waypoint you want to purchase the ship at.",
 *       "type": "string"
 *     }
 *   },
 *   "required": [
 *     "shipType",
 *     "waypointSymbol"
 *   ],
 *   "type": "object"
 * }
 */
export interface PurchaseShipRequest {

    shipType: ShipType;

    /**
     * The symbol of the waypoint you want to purchase the ship at.
     */
    waypointSymbol: string;

}
