/**
 * This file was generated by st-open-api
 */
import { ShipRefineRequestProduce } from './ShipRefineRequestProduce'

/**
 * Open-api schema
 * {
 *   "properties": {
 *     "produce": {
 *       "type": "string",
 *       "enum": [
 *         "IRON",
 *         "COPPER",
 *         "SILVER",
 *         "GOLD",
 *         "ALUMINUM",
 *         "PLATINUM",
 *         "URANITE",
 *         "MERITIUM",
 *         "FUEL"
 *       ]
 *     }
 *   },
 *   "required": [
 *     "produce"
 *   ],
 *   "type": "object"
 * }
 */
export interface ShipRefineRequest {

    produce: ShipRefineRequestProduce;

}
