/**
 * This file was generated by st-open-api
 */
import {ICooldown} from '../../components/i-cooldown';
import {IShipNav} from '../../components/i-ship-nav';

export interface IDataJumpShipResponse {

    cooldown: ICooldown;

    nav?: IShipNav;

}
