/**
 * This file was generated by st-open-api
 */
import {IShipFuel} from '../../components/i-ship-fuel';
import {IShipNav} from '../../components/i-ship-nav';

export interface IDataNavigateShipResponse {

    fuel: IShipFuel;

    nav: IShipNav;

}
