/**
 * This file was generated by st-open-api
 */
import {IAgent} from '../../components/i-agent';
import {IContract} from '../../components/i-contract';
import {IFaction} from '../../components/i-faction';
import {IShip} from '../../components/i-ship';

export interface IDataRegisterResponse {

    agent: IAgent;

    contract: IContract;

    faction: IFaction;

    ship: IShip;

    token: string;

}
