/**
 * This file was generated by st-open-api
 */
import {IAgent} from '../../components/i-agent';
import {IShipyardTransaction} from '../../components/i-shipyard-transaction';
import {IShip} from '../../components/i-ship';

export interface IDataPurchaseShipResponse {

    agent: IAgent;

    ship: IShip;

    transaction: IShipyardTransaction;

}
