/**
 * This file was generated by st-open-api
 */
import {ICooldown} from '../../components/i-cooldown';

export interface IDataCreateShipWaypointScanResponse {

    cooldown: ICooldown;

    waypoints: Array<any>;

}
