/**
 * This file was generated by st-open-api
 */
import {ICooldown} from '../../components/i-cooldown';
import {IExtraction} from '../../components/i-extraction';
import {IShipCargo} from '../../components/i-ship-cargo';

export interface IDataExtractResourcesResponse {

    cargo: IShipCargo;

    cooldown: ICooldown;

    extraction: IExtraction;

}
