/**
 * This file was generated by st-open-api
 */
import {IAgent} from '../../components/i-agent';
import {IContract} from '../../components/i-contract';

export interface IDataFulfillContractResponse {

    agent: IAgent;

    contract: IContract;

}
