/**
 * This file was generated by st-open-api
 */
import {IContract} from '../../components/i-contract';
import {IShipCargo} from '../../components/i-ship-cargo';

export interface IDataDeliverContractResponse {

    cargo: IShipCargo;

    contract: IContract;

}
