/**
 * This file was generated by st-open-api
 */
import {ICooldown} from '../../components/i-cooldown';

export interface IDataCreateSurveyResponse {

    cooldown: ICooldown;

    surveys: Array<any>;

}
