/**
 * This file was generated by st-open-api
 */
import {ICooldown} from '../../components/i-cooldown';

export interface IDataCreateShipShipScanResponse {

    cooldown: ICooldown;

    ships: Array<any>;

}
