/**
 * This file was generated by st-open-api
 */
import {IChart} from '../../components/i-chart';
import {IWaypoint} from '../../components/i-waypoint';

export interface IDataCreateChartResponse {

    chart: IChart;

    waypoint: IWaypoint;

}
