/**
 * This file was generated by st-open-api
 */
import {IAgent} from '../../components/i-agent';
import {IShipFuel} from '../../components/i-ship-fuel';

export interface IDataRefuelShipResponse {

    agent: IAgent;

    fuel: IShipFuel;

}
