/**
 * This file was generated by st-open-api
 */
import {ICooldown} from '../../components/i-cooldown';

export interface IDataCreateShipSystemScanResponse {

    cooldown: ICooldown;

    systems: Array<any>;

}
