/**
 * This file was generated by st-open-api
 */
import {IAgent} from '../../components/i-agent';
import {IMarketTransaction} from '../../components/i-market-transaction';
import {IShipCargo} from '../../components/i-ship-cargo';

export interface IDataSellCargoResponse {

    agent: IAgent;

    cargo: IShipCargo;

    transaction: IMarketTransaction;

}
